HIDDEN_LAYER_NEURONS = [5]
N_SNAKE = 10000
# simulate until N_DEATH deaths
N_DEATH = int(0.95 * N_SNAKE)
# select best N_CROSS snakes
N_CROSS = int(0.1 * N_SNAKE)
N_CLASS = 3
BORDER = 6
DNA_SIZE = (BORDER**2+3)*HIDDEN_LAYER_NEURONS[0]
for i in range(len(HIDDEN_LAYER_NEURONS)-1):
    DNA_SIZE += HIDDEN_LAYER_NEURONS[i]*HIDDEN_LAYER_NEURONS[i+1]
DNA_SIZE += HIDDEN_LAYER_NEURONS[-1]*N_CLASS
MUTATION_RATE = 1/(DNA_SIZE)
ITERATION = 500
MUTATION_PROBABILITY = 0.0001
SCALE = 20



