class Conf():
    HIDDEN_LAYER_NEURONS = [6]
    N_SNAKE = 10000
    N_DEATH = 5000
    N_CROSS = 1000
    N_CLASS = 3
    BORDER = 10
    DNA_SIZE = (BORDER**2+3)*HIDDEN_LAYER_NEURONS[0]
    for i in range(len(HIDDEN_LAYER_NEURONS)-1):
        DNA_SIZE += HIDDEN_LAYER_NEURONS[i]*HIDDEN_LAYER_NEURONS[i+1]
    DNA_SIZE += HIDDEN_LAYER_NEURONS[-1]*N_CLASS
    MUTATION_RATE = 1/(DNA_SIZE)
    ITERATION = 50
    MUTATION_PROBABILITY = 0.0001
    SCALE = 20
    


